services:
  db:
    container_name: teste_guia_db
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./prisma/sql/:/docker-entrypoint-initdb.d/

  analysis:
    build: .
    depends_on:
      - db
    container_name: analysis_runner
    restart: on-failure
    env_file: .env 

volumes:
  postgres:
